---
- name: Add the user with password and key
  hosts: web
  #become: yes
  roles:
    - { role: adduser, tags: [addusers] }
    - { role: sshd, tags: [sshd] }
    - { role: sudo, tags: [sudo] }
    - { role: apt_php, tags: [php] }
    - { role: php_configure, tags: [php_configure] }
    - { role: redis, tags: [redis] }
