---
- name: Create a new WP database
  mysql_db:
    name: "{{wp_db_name_and_user}}"
    collation: "utf8_general_ci"
    encoding: "utf8"
    state: present

- name: Add WP user
  mysql_user:
    user: "{{ wp_db_name_and_user }}"
    password: "{{ wp_db_passwd }}"
    host: "{{ item }}"
    priv: "{{ wp_db_name_and_user }}.*:ALL"
  no_log: mariadb_debug == false
  changed_when: false # required for idempotence
  with_items: "{{ mariadb_default_hosts }}"
