---
- name: install system updates for ubuntu systems
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install for https transport for debian apt tool
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - aptitude

- name: Install system tools
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - lsb-release
      - mc
      - htop
      - git
      - util-linux
      - moreutils
      - curl
      - unzip
      - console-setup
      - tzdata
      - mosh
      - vsftpd
      - iptables-persistent
      - whois
      - net-tools
      - liblz4-tool
      - python-setuptools
      - ncdu
      - lynx
      - ntp
      - sshfs
      - xfsprogs
      - ntpdate
      - unattended-upgrades
      - apt-mirror
      - optipng
      - jpegoptim
      - pngcrush
      - gifsicle
      - pngquant
      - libjpeg-progs
      - bc
      - dstat
      - ioping

- name: Install PHP 7.2
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - php7.2
        - php-amqp
        - php-amqplib
        - php-auth-sasl
        - php7.2-bcmath
        - php7.2-bz2
        - php7.2-cli
        - php7.2-common
        - php7.2-curl
        - php7.2-fpm
        - php7.2-gd
        - php7.2-imap
        - php-common
        - php7.2-intl
        - php7.2-json
        - php7.2-mbstring
        - php7.2-mysql
        - php7.2-opcache
        - php7.2-pgsql
        - php7.2-pspell
        - php7.2-xmlrpc
        - php7.2-xml
        - php7.2-xsl
        - php7.2-soap
        - php7.2-tidy
        - php7.2-recode
        - php-php-gettext
        - php7.2-zip
        - php-pear
        - php-oauth
        - php7.2-readline
        - librecode0
        - libsodium23
        - libtidy5
        - libzip4
        - php-cli
        - php-common
        - php-mbstring
        - php-xml
        - fontconfig-config
        - fonts-dejavu-core
        - libc-client2007e
        - libfontconfig1
        - libgd3
        - libjbig0
        - librabbitmq4
        - libsodium23
        - libtiff5
        - libwebp6
        - libxpm4
        - mlock
        - aspell
        - aspell-en
        - libaspell15
        - libpq5
        - libxmlrpc-epi0
        - composer
        - jsonlint
        - php-cli-prompt
        - php-composer-ca-bundle
        - php-composer-semver
        - php-composer-spdx-licenses
        - php-json-schema
        - php-psr-log
        - php-symfony-console
        - php-symfony-debug
        - php-symfony-filesystem
        - php-symfony-finder
        - php-symfony-polyfill-mbstring
        - php-symfony-process

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
