---
- name: Gathering memory from the new server
  setup:
    filter: ansible_memtotal_mb
    gather_subset:
      - hardware

- name: Gathering facts on number CPUs from the new server
  setup:
    filter: ansible_processor_vcpus
    gather_subset:
      - hardware

