---
- name: add rabbitmq repository trusted key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: add rabbitmq official apt repository
  apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release | lower }} main'
    state: present

- name: install rabbitmq packages
  apt:
    update_cache: yes
    #cache_valid_time: 3600
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - rabbitmq-server
      - python3-software-properties

- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled
  notify:
  - restart rabbitmq

- name: add users
  rabbitmq_user:
    user: "{{item}}"
    password: "{{rabbitmq_pass}}"
    tags: administrator,"{{item}}"
    vhost: /
    configure_priv: =.* write_priv=.* read_priv=.*
    state: present
  with_items:
    - "{{rabbitmq_user}}"

- name: remove default guest user
  rabbitmq_user:
    user: guest
    state: absent

- name: ensure vhost /test is present
  rabbitmq_vhost:
    name: /test
    state: present
